services:
  backend:
    build: ./backend
    container_name: nemesis-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/models:/app/models
    environment:
      - ORIGENES_FRONTEND_PERMITIDOS=http://localhost:5173
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # network_mode: host  <-- Comenta o borra esta línea

  frontend:
    build: ./frontend
    container_name: nemesis-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
